name: Deploy LAMP Application to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  
      
      
      - name: Authenticate to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 688567291323.dkr.ecr.ap-south-1.amazonaws.com/lamp-app:latest
          context: .


     # Download the current ECS task definition
      - name: Download task definition
        id: download-task
        run: |
          aws ecs describe-task-definition \
            --task-definition ecs-lamp-task \
            --query taskDefinition \
            --output json > task-definition.json
          echo "task-definition=task-definition.json" >> $GITHUB_OUTPUT

      # Update the task definition with the new Docker image
      - name: Update task definition
        id: update-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: lamp-app-container  # Correct container name from your task definition
          image: 688567291323.dkr.ecr.ap-south-1.amazonaws.com/lamp-app:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition:  ${{ steps.update-task.outputs.task-definition }}
          service: ecs-lamp-services
          cluster: ecs-lamp-cluster
          wait-for-service-stability: true
