name: Deploy LAMP Application to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  
      
      
      - name: Authenticate to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 688567291323.dkr.ecr.ap-south-1.amazonaws.com/lamp-app:latest
          context: .


      - name: Register Task Definition
        run: |
          echo "${{ secrets.LAMP_TASK_DEFINITION }}" > lamp-task.json
          aws ecs register-task-definition \
            --family lamp-task \
            --container-definitions file://lamp-task.json \
            --region ap-south-1

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-lamp-task.json
          service: ecs-lamp-services
          cluster: ecs-lamp-cluster
          region: ap-south-1
