name: Deploy LAMP Application to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Hardcoded AWS Region for debugging

      - name: Print Secrets
        run: |
          echo "AWS_REGION=ap-south-1"
          echo "ECR_REPOSITORY_URI=688567291323.dkr.ecr.ap-south-1.amazonaws.com/lamp-app"

      - name: Authenticate to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin 688567291323.dkr.ecr.ap-south-1.amazonaws.com/lamp-app

      - name: Build Docker Image
        run: |
          docker build -t lamp-app .
          docker tag lamp-app:latest 688567291323.dkr.ecr.ap-south-1.amazonaws.com/lamp-app:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 688567291323.dkr.ecr.ap-south-1.amazonaws.com/lamp-app:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: lamp-task
          service: lamp-service
          cluster: lamp-cluster
          region: ap-south-1
